alias gc='git commit -m '
alias gca='git commit --amend'
alias gss='git status'
alias gl='git log --oneline --graph'
alias glog='git log --graph --pretty=format:'\''%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset'\'' --abbrev-commit'
alias gl6='glog -n 6'
alias ga='git add'
alias gb='git branch'
alias gaa='git add .'
alias co='git checkout'
alias com='git checkout main'
